"""
Django settings for ai_interview project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os # Add os import
import dj_database_url # Add dj_database_url import
from dotenv import load_dotenv # Add dotenv import
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (optional, useful for local dev)
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Using a HARDCODED dummy key for testing/college project as requested.
# DO NOT use this key in a real production environment!
SECRET_KEY = 'dummy-secret-key-for-testing-ai-interview-project' # Dummy Key

# SECURITY WARNING: don't run with debug turned on in production!
# Get DEBUG from environment variable (default to False for production)
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Get ALLOWED_HOSTS from environment variable, split by comma
allowed_hosts_str = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# Add Render and Vercel hostnames for production, plus defaults for local dev
# Render provides a '.onrender.com' domain by default
# Vercel provides '.vercel.app'
ALLOWED_HOSTS.extend([
    '127.0.0.1',
    'localhost',
    '.onrender.com', # Add Render default domain pattern
    '.vercel.app', # Keep Vercel domain pattern
])

# Add CSRF trusted origins from environment variable
csrf_trusted_origins_str = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_origins_str.split(',') if origin.strip()]

# Add Render and Vercel origins
CSRF_TRUSTED_ORIGINS.extend([
    'https://*.onrender.com',
    'https://*.vercel.app',
])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # Removed 'corsheaders'
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rest_framework',
    # Register apps using AppConfig paths
    'users.apps.UsersConfig',
    'jobs.apps.JobsConfig',
    'quiz.apps.QuizConfig',
    'predictor.apps.PredictorConfig', # Add the new predictor app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Removed 'corsheaders.middleware.CorsMiddleware'
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_interview.urls'

# Removed duplicate os import

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Add top-level templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_interview.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configure database using DATABASE_URL environment variable
DATABASES = {
    'default': dj_database_url.config(
        # Fallback to SQLite for local development if DATABASE_URL not set
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600 # Optional: connection pooling
    )
}

# Removed check for SECRET_KEY environment variable


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# Place static files collected by collectstatic into this directory
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Enable Whitenoise storage for optimized static file handling
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Custom Settings ---

# Google AI API Key
# Load from environment variable
GOOGLE_AI_API_KEY = os.environ.get('GOOGLE_AI_API_KEY')

# Raise error if GOOGLE_AI_API_KEY is not set in production
if not DEBUG and not GOOGLE_AI_API_KEY:
    raise ValueError("GOOGLE_AI_API_KEY environment variable must be set in production")


# Tell Django to use the custom User model
AUTH_USER_MODEL = 'users.User'

# Removed duplicate Gemini API Key entry

# Media files (User Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Store media files in a 'media' directory at the project root


# Removed CORS Settings section
